### ISSUE TITLE
input as="select" no work with namespace collection

### ISSUE THREAD

**Issue by mazhack** [dockyard/ember-easy-form#110]
Hi, i have some problems with select, i create the model and controller

```javascript
App.someOptions = [ {
    'id' : 'id_a',
    'val' : 'a'
  }, {
    'id' : 'id_b',
    'val' : 'b'
  }, {
    'id' : 'id_c',
    'val' : 'c'
  }, {
    'id' : 'id_d',
    'val' : 'd'
  } ];
  
  App.SomeObject = Ember.Object.extend({ 
    dira: 'id_a',
    dirb: '',
    someOptions : [ {
      'id' : 'id_a',
      'val' : 'a'
    }, {
      'id' : 'id_b',
      'val' : 'b'
    }, {
      'id' : 'id_c',
      'val' : 'c'
    }, {
      'id' : 'id_d',
      'val' : 'd'
    } ]  
  });
  
  App.SomeController = Ember.ArrayController.extend({    
    model : null,    
    init : function() {
      this._super();
      this.set('model', App.SomeObject.create());
    }
  });
```
the template is:

```html
{{#form-for model}}
  {{input dira as="select"
    collection="someOptions"
    optionLabelPath="content.val"
    optionValuePath="content.id"
  }}
  {{input dirb as="select"
    collection="App.someOptions"
    optionLabelPath="content.val"
    optionValuePath="content.id"
  }}
}}
```
first input work fine, but the second select not render options, i try with ember select view and its work fine:
```html
{{view Ember.Select
    contentBinding="App.someOptions"
    selectionBinding="App.someObject.letterSelection"
    optionLabelPath="content.val"
    optionValuePath="content.id"
  }}
```
to fix it i change the function modelPropertyPath in "input-field" helper
```
var modelPropertyPath = function(property) {
    if(!property) { return null; }
    
    var startsWith = property.split('.')[0];
    
    var startsWithKeyword = !!options.data.keywords[startsWith];

    if (startsWithKeyword) {
      return property;
    }

    var startsWithNamespace = !!Ember.Namespace.byName(startsWith);
    
    if(startsWithNamespace) {
      return property;
    }
    
    if (modelPath) {
      return modelPath + '.' + property;
    } else {
      return property;
    }
  };
``` 
So, fix the doc or fix the helper or say me how to use the select. thanks.
PD. sorry my english is bad..

**Comment by diogomafra** [comment]
I'm closing this issue because we don't have direct support for the select component in the library anymore, and because it is a very old issue. :smile: 

----

Most of the code of the library was rewritten to be an Ember addon compatible with Ember 1.13.

The select view was deprecated on Ember 1.13 and removed on Ember 2.0. To support both versions we had to remove the direct support for it. You can define a custom input helper using any select component you want.

Here is a gist showing how to write a custom input type for the `select` component: https://gist.github.com/diogomafra/9c2b3e2fc1f3dcff59f0

You can get the most recent version of ember-easy-form on the branch `1-0-stable` or as an ember-addon [here](https://www.npmjs.com/package/ember-easy-form).
