### ISSUE TITLE
HTML5 input attribute support

### ISSUE THREAD

**Issue by ahacking** [dockyard/ember-easy-form#118]
I am using ember-easyForm in anger and it didn't take long to discover that most of the HTML5 input attributes are not supported.

As a workaround I am patching ``Ember.EasyForm.Input`` with the current attributes 'placeholder' and 'prompt' and the known html5 attributes as follows:

```
Em.EasyForm.Input.reopen({
  bindableInputOptions: [
    'accept', 'align', 'alt', 'autocomplete', 'autofocus',
    'checked', 'disabled', 'form', 'formaction', 'formenctype',
    'formmethod', 'formnovalidate', 'formtarget', 'height', 'list',
    'max', 'maxlength', 'min', 'multiple', 'pattern', 'placeholder',
    'prompt', 'readonly', 'required', 'size', 'src', 'step', 'width'
  ]
});
```

I am aware that a number of the above attributes are only applicable to certain input types but I also don't think we should bloat the runtime to detect use of invalid html attributes on the wrong semantic type.

Is there any reason the above html5 attributes are not supported by default?

**Comment by diogomafra** [comment]
Most of the code of the library was rewritten to be compatible with Ember 1.13, and this is already fixed in the most recent version.

You can get the most recent version of ember-easy-form on the branch `1-0-stable` or as an ember-addon [here](https://www.npmjs.com/package/ember-easy-form).

Make sure to read the README and CHANGELOG on the 1-0-stable branch.
