### ISSUE TITLE
Show Select example with none absolute path

### ISSUE THREAD

**Issue by ZenCocoon** [dockyard/ember-easy-form#173]
The example on the Read Me to use the select input is a bit confusing as using global namespace, I would present it with a controller value, for example:

```
{{input currency as="select"
        collection='controller.currencies'
        value='currency'
        optionValuePath="content.code"
        optionLabelPath="content.fullname"
      }}
```

**Comment by diogomafra** [comment]
I'm closing this issue because we don't have direct support for the select component in the library anymore, and because it is a very old issue. :smile: 

----

Most of the code of the library was rewritten to be an Ember addon compatible with Ember 1.13.

The select view was deprecated on Ember 1.13 and removed on Ember 2.0. To support both versions we had to remove the direct support for it. You can define a custom input helper using any select component you want.

Here is a gist showing how to write a custom input type for the `select` component: https://gist.github.com/diogomafra/9c2b3e2fc1f3dcff59f0

You can get the most recent version of ember-easy-form on the branch `1-0-stable` or as an ember-addon [here](https://www.npmjs.com/package/ember-easy-form).
