### ISSUE TITLE
Select input value

### ISSUE THREAD

**Issue by yratanov** [dockyard/ember-easy-form#182]
```handlebars
{{input field as="select" collection='someCollection'}}
```

Doesn't bind value, but

```handlebars
{{input field value='field' as="select" collection='someCollection'}}
```

does.

I believe the problem is here: https://github.com/dockyard/ember-easyForm/blob/master/packages/ember-easyForm/lib/helpers/input-field.js#L64 .

If I remove ```delete(options.hash.valueBinding);``` and ``` options.hash.valueBinding     = modelPropertyPath(options.hash.value);``` everything is working as expected.

**Comment by diogomafra** [comment]
I'm closing this issue because we don't have direct support for the select component in the library anymore, and because it is a very old issue. :smile: 

----

Most of the code of the library was rewritten to be an Ember addon compatible with Ember 1.13.

The select view was deprecated on Ember 1.13 and removed on Ember 2.0. To support both versions we had to remove the direct support for it. You can define a custom input helper using any select component you want.

Here is a gist showing how to write a custom input type for the `select` component: https://gist.github.com/diogomafra/9c2b3e2fc1f3dcff59f0

You can get the most recent version of ember-easy-form on the branch `1-0-stable` or as an ember-addon [here](https://www.npmjs.com/package/ember-easy-form).
