### ISSUE TITLE
Select input is always selected on "Please select"

### ISSUE THREAD

**Issue by jackmatt2** [dockyard/ember-easy-form#188]
I started getting weird behaviour from the select element, not exactly sure when this happened.  

```
//bower dependency
    "ember-easyForm": "http://builds.dockyard.com.s3.amazonaws.com/ember-easyForm/latest/ember-easyForm.prod.js",  
```

For the select below,

```javascript
                        	{{input employee as="select"
                        	name="employee"
                        	selection="controller.employee"
                        	collection="controller.employees"
                        	optionLabelPath="content.name"
                        	optionValuePath="content.id"
                        	prompt="Please select"
                        	disabled=false
                        	}}
```

I can see the model updating correctly as I change the option in the select, however, the actual select element is always selected on the "Please select" option.  Any ideas?

The other thing is that in the debugger I can see that none of the options have the `selected` attribute.

update
---------
I will add this also because I think it is important.  I am using a Bootstrap Modal with a single controller to render these select elements as described [here](http://emberjs.com/guides/cookbook/user_interface_and_interaction/using_modal_dialogs/).  As controllers are singletons I am updating the list of employees that is bound to the current model like so.

```javascript
    employees : function() {
        var load = this.get('model');
        return this.store.find('employee', {site : load.get('fromSite').get('id')});
    }.property('model'),
```

This might be related to the issue as selects elsewhere in the application are working fine.

**Comment by diogomafra** [comment]
I'm closing this issue because we don't have direct support for the select component in the library anymore, and because it is a very old issue. :smile: 

----

Most of the code of the library was rewritten to be an Ember addon compatible with Ember 1.13.

The select view was deprecated on Ember 1.13 and removed on Ember 2.0. To support both versions we had to remove the direct support for it. You can define a custom input helper using any select component you want.

Here is a gist showing how to write a custom input type for the `select` component: https://gist.github.com/diogomafra/9c2b3e2fc1f3dcff59f0

You can get the most recent version of ember-easy-form on the branch `1-0-stable` or as an ember-addon [here](https://www.npmjs.com/package/ember-easy-form).
